config/routes.rb
ReefWatchApp::Application.routes.draw do
  resources :alarm_codes


  resources :alarm_notifications


  resources :livestock_imports


  resources :equipment_imports


  resources :livestocks do
    collection { post :delete_all}
  end 
    


  resources :equipment  do
    collection { post :delete_all}
  end
   
 

  resources :reef_tanks


  resources :watchers
 root :to => "reef_tanks#index"

  authenticated :user do
   root :to => "reef_tanks#index"
  end
 
  devise_for :users
  resources :users
end

app/models/reef_tank.rb
class ReefTank < ActiveRecord::Base
  attr_accessible :current_temp, :last_update, :setup_date, :tank_name, :temp_name
end

app/controllers/reef_tanks_controller.rb
class ReefTanksController < ApplicationController
  # GET /reef_tanks
  # GET /reef_tanks.json
  def index
    @reef_tanks = ReefTank.all
    @watchers = Watcher.first
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reef_tanks }
    end
  end

  # GET /reef_tanks/1
  # GET /reef_tanks/1.json
  def show
    @reef_tank = ReefTank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reef_tank }
    end
  end

  # GET /reef_tanks/new
  # GET /reef_tanks/new.json
  def new
    @reef_tank = ReefTank.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reef_tank }
    end
  end

  # GET /reef_tanks/1/edit
  def edit
    @reef_tank = ReefTank.find(params[:id])
  end

  # POST /reef_tanks
  # POST /reef_tanks.json
  def create
    @reef_tank = ReefTank.new(params[:reef_tank])

    respond_to do |format|
      if @reef_tank.save
        format.html { redirect_to @reef_tank, notice: 'Reef tank was successfully created.' }
        format.json { render json: @reef_tank, status: :created, location: @reef_tank }
      else
        format.html { render action: "new" }
        format.json { render json: @reef_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reef_tanks/1
  # PUT /reef_tanks/1.json
  def update
    @reef_tank = ReefTank.find(params[:id])

    respond_to do |format|
      if @reef_tank.update_attributes(params[:reef_tank])
        format.html { redirect_to @reef_tank, notice: 'Reef tank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reef_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reef_tanks/1
  # DELETE /reef_tanks/1.json
  def destroy
    @reef_tank = ReefTank.find(params[:id])
    @reef_tank.destroy

    respond_to do |format|
      format.html { redirect_to reef_tanks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reef_tanks_helper.rb
module ReefTanksHelper
end

app/views/reef_tanks/_form.html.erb
<%= simple_form_for @reef_tank, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :tank_name %>
  <%= f.input :setup_date %>
  <%= f.input :last_update %>
  <%= f.input :current_temp %>
  <%= f.input :temp_name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reef_tanks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reef_tanks/edit.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reef_tanks/index.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
	
	
	<tr style="border-top: 1px solid #eee; padding-top: 5px; margin-top: 5px">
	  <td class="fancy-date ">
	  <div class="fancy-weekday">
		
	                                             Temp
	</div>
    <div class="fancy-day">
 
	  	<% if (@watchers != nil) then %>
		 <%= @watchers.temp %> 
		<% else %>
	 
		<% end %>
	        
 
     </div>
	 </td>
	
	<td class="fancy-date ">
		Last Updated:
		<% if (@watchers != nil) then %>
		 <%= time_ago_in_words(@watchers.created_at) %>  ago  
		<% else %>
	 
		<% end %>
		
		
	</td>
	     </tr>                              
	
	
	
	
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tank_name) %></th>
      <th><%= model_class.human_attribute_name(:setup_date) %></th>
      <th><%= model_class.human_attribute_name(:last_update) %></th>
      <th><%= model_class.human_attribute_name(:current_temp) %></th>
      <th><%= model_class.human_attribute_name(:temp_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reef_tanks.each do |reef_tank| %>
      <tr>
        <td><%= link_to reef_tank.id, reef_tank_path(reef_tank) %></td>
        <td><%= reef_tank.tank_name %></td>
        <td><%= reef_tank.setup_date %></td>
        <td><%= reef_tank.last_update %></td>
        <td><%= reef_tank.current_temp %></td>
        <td><%= reef_tank.temp_name %></td>
        <td><%=l reef_tank.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reef_tank_path(reef_tank), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reef_tank_path(reef_tank),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reef_tank_path,
            :class => 'btn btn-primary' %>

app/views/reef_tanks/new.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reef_tanks/show.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tank_name) %>:</strong></dt>
  <dd><%= @reef_tank.tank_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:setup_date) %>:</strong></dt>
  <dd><%= @reef_tank.setup_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_update) %>:</strong></dt>
  <dd><%= @reef_tank.last_update %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_temp) %>:</strong></dt>
  <dd><%= @reef_tank.current_temp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:temp_name) %>:</strong></dt>
  <dd><%= @reef_tank.temp_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reef_tanks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reef_tank_path(@reef_tank), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reef_tank_path(@reef_tank),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>