config/routes.rb
ReefWatchApp::Application.routes.draw do
  resources :alarm_codes


  resources :alarm_notifications


  resources :livestock_imports


  resources :equipment_imports


  resources :livestocks do
    collection { post :delete_all}
  end 
    


  resources :equipment  do
    collection { post :delete_all}
  end
   
 

  resources :reef_tanks


  resources :watchers
 root :to => "reef_tanks#index"

  authenticated :user do
   root :to => "reef_tanks#index"
  end
 
  devise_for :users
  resources :users
end

app/models/alarm_code.rb
class AlarmCode < ActiveRecord::Base
  attr_accessible :message, :tank_name, :sent_email, :h_code, :email,  :display_site_wide,  :priority,  :message_2
  
  belongs_to :watcher, :primary_key => :h_code , :foreign_key => :a_code
end


 

app/controllers/alarm_codes_controller.rb
class AlarmCodesController < ApplicationController
  # GET /alarm_codes
  # GET /alarm_codes.json
  def index
    @alarm_codes = AlarmCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alarm_codes }
    end
  end

  # GET /alarm_codes/1
  # GET /alarm_codes/1.json
  def show
    @alarm_code = AlarmCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alarm_code }
    end
  end

  # GET /alarm_codes/new
  # GET /alarm_codes/new.json
  def new
    @alarm_code = AlarmCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alarm_code }
    end
  end

  # GET /alarm_codes/1/edit
  def edit
    @alarm_code = AlarmCode.find(params[:id])
  end

  # POST /alarm_codes
  # POST /alarm_codes.json
  def create
    @alarm_code = AlarmCode.new(params[:alarm_code])

    respond_to do |format|
      if @alarm_code.save
        format.html { redirect_to @alarm_code, notice: 'Alarm code was successfully created.' }
        format.json { render json: @alarm_code, status: :created, location: @alarm_code }
      else
        format.html { render action: "new" }
        format.json { render json: @alarm_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alarm_codes/1
  # PUT /alarm_codes/1.json
  def update
    @alarm_code = AlarmCode.find(params[:id])

    respond_to do |format|
      if @alarm_code.update_attributes(params[:alarm_code])
        format.html { redirect_to @alarm_code, notice: 'Alarm code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alarm_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarm_codes/1
  # DELETE /alarm_codes/1.json
  def destroy
    @alarm_code = AlarmCode.find(params[:id])
    @alarm_code.destroy

    respond_to do |format|
      format.html { redirect_to alarm_codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alarm_codes_helper.rb
module AlarmCodesHelper
end

app/views/alarm_codes/_form.html.erb
<%= simple_form_for @alarm_code, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :tank_name %>
  <%= f.input :h_code %>
  <%= f.input :message %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                alarm_codes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/alarm_codes/edit.html.erb
<%- model_class = AlarmCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alarm_codes/index.html.erb
<%- model_class = AlarmCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tank_name) %></th>
      <th><%= model_class.human_attribute_name(:h_code) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @alarm_codes.each do |alarm_code| %>
      <tr>
        <td><%= link_to alarm_code.id, alarm_code_path(alarm_code) %></td>
        <td><%= alarm_code.tank_name %></td>
        <td><%= alarm_code.h_code %></td>
        <td><%= alarm_code.message %></td>
        <td><%=l alarm_code.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_alarm_code_path(alarm_code), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      alarm_code_path(alarm_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_alarm_code_path,
            :class => 'btn btn-primary' %>

app/views/alarm_codes/new.html.erb
<%- model_class = AlarmCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alarm_codes/show.html.erb
<%- model_class = AlarmCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tank_name) %>:</strong></dt>
  <dd><%= @alarm_code.tank_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:h_code) %>:</strong></dt>
  <dd><%= @alarm_code.h_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message) %>:</strong></dt>
  <dd><%= @alarm_code.message %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              alarm_codes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_alarm_code_path(@alarm_code), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              alarm_code_path(@alarm_code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>