config/routes.rb
ReefWatchApp::Application.routes.draw do
  resources :alarm_codes


  resources :alarm_notifications


  resources :livestock_imports


  resources :equipment_imports


  resources :livestocks do
    collection { post :delete_all}
  end 
    


  resources :equipment  do
    collection { post :delete_all}
  end
   
 

  resources :reef_tanks


  resources :watchers
 root :to => "reef_tanks#index"

  authenticated :user do
   root :to => "reef_tanks#index"
  end
 
  devise_for :users
  resources :users
end

app/models/livestock.rb
class Livestock < ActiveRecord::Base
  attr_accessible :common_name, :description, :image, :livestock_type, :scientific_name


end

app/controllers/livestocks_controller.rb
class LivestocksController < ApplicationController
  # GET /livestocks
  # GET /livestocks.json
  def index
    #@livestocks = Livestock.all
    @livestocks = Livestock.paginate(page: params[:page], :per_page => 100)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @livestocks }
    end
  end

  
  def import
    Livestock.import(params[:file])
    redirect_to root_url, notice: "Livestocks imported."
  end
  
  # GET /livestocks/1
  # GET /livestocks/1.json
  def show
    @livestock = Livestock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @livestock }
    end
  end

  # GET /livestocks/new
  # GET /livestocks/new.json
  def new
    @livestock = Livestock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @livestock }
    end
  end

  # GET /livestocks/1/edit
  def edit
    @livestock = Livestock.find(params[:id])
  end

  # POST /livestocks
  # POST /livestocks.json
  def create
    @livestock = Livestock.new(params[:livestock])

    respond_to do |format|
      if @livestock.save
        format.html { redirect_to @livestock, notice: 'Livestock was successfully created.' }
        format.json { render json: @livestock, status: :created, location: @livestock }
      else
        format.html { render action: "new" }
        format.json { render json: @livestock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /livestocks/1
  # PUT /livestocks/1.json
  def update
    @livestock = Livestock.find(params[:id])

    respond_to do |format|
      if @livestock.update_attributes(params[:livestock])
        format.html { redirect_to @livestock, notice: 'Livestock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @livestock.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @livestock = Livestock.find(params[:id])
    @livestock.destroy

    respond_to do |format|
      format.html { redirect_to livestocks_url }
      format.json { head :no_content }
    end
  end

  def delete_all
    Livestock.delete_all

    respond_to do |format|
      format.html { redirect_to livestocks_url, notice: 'Livestock Table was erased.'  }
      format.json { head :no_content }
    end
  end

end

app/helpers/livestocks_helper.rb
module LivestocksHelper
end

app/views/livestocks/_form.html.erb
<%= simple_form_for @livestock, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :description %>
  <%= f.input :common_name %>
  <%= f.input :scientific_name %>
  <%= f.input :image %>
  <%= f.input :livestock_type %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                livestocks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/livestocks/edit.html.erb
<%- model_class = Livestock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/livestocks/index.html.erb
<%- model_class = Livestock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
    
      <th><%= model_class.human_attribute_name(:common_name) %></th>
      <th><%= model_class.human_attribute_name(:scientific_name) %></th>
  
      <th><%= model_class.human_attribute_name(:livestock_type) %></th>
   
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @livestocks.each do |livestock| %>
      <tr>
        <td><%= link_to livestock.id, livestock_path(livestock) %></td>
    
        <td><%= livestock.common_name %></td>
        <td><%= livestock.scientific_name %></td>
   
        <td><%= livestock.livestock_type %></td>
    
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_livestock_path(livestock), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      livestock_path(livestock),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<h2>Import LiveStock</h2>

<p><%= link_to "Import LiveStock", new_livestock_import_path %></p>


<%= link_to t('.delete_all', :default => t("helpers.links.destroy all")),
              delete_all_livestocks_path,
              :method => :delete_all,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>

		


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_livestock_path,
            :class => 'btn btn-primary' %>

app/views/livestocks/new.html.erb
<%- model_class = Livestock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/livestocks/show.html.erb
<%- model_class = Livestock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @livestock.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:common_name) %>:</strong></dt>
  <dd><%= @livestock.common_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scientific_name) %>:</strong></dt>
  <dd><%= @livestock.scientific_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @livestock.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:livestock_type) %>:</strong></dt>
  <dd><%= @livestock.livestock_type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              livestocks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_livestock_path(@livestock), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              livestock_path(@livestock),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>